name: DropBox API Workflow

on:
  workflow_dispatch

jobs:
  authenticate_and_access_dropbox:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with DropBox API
        run: |
            Result= $(curl -X POST https://api.dropboxapi.com/2/files/list_folder \
                -u "${{ secrets.DROPBOX_APP_KEY  }}:${{ secrets.DROPBOX_APP_SECRET }}" \
                --header "Content-Type: application/json" \
                --data "{\"include_deleted\":false,\"include_has_explicit_shared_members\":false,\"include_media_info\":false,\"include_mounted_folders\":true,\"include_non_downloadable_files\":true,\"path\":\"/vending-machine-project-releases\",\"recursive\":false}")
            echo "Result -> $Result"    
