name: Create Release

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v2

    - name: Download RC Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}

    - name: Extract Version
      run: |
        version=$(cat ./bin/app-data.js | grep -oP '(?<="version": ")[^"]*')
        echo "Preparing version $version for release"
        echo "VERSION=$version" >> $GITHUB_ENV

    #- name: Create Release
    #  id: create_release
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    tag_name: ${{ env.VERSION }}
    #    release_name: Release ${{ env.VERSION }}
    #    body: |
    #      Release ${{ env.VERSION }}
    #    draft: false
    #    prerelease: false

    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ${{ inputs.artifact_name }}
    #    path: path/to/artifact
