name: Create Release

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true
permissions:
  contents: write

jobs:
  create_release:
    concurrency:
      group: create_release
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Run ID For Artifact    
      id: fetch-runid
      run: |
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=fester-honker" | jq -r '.artifacts[0].workflow_run.id')
        echo "run_id of workflow that produced the artifact is $run_id"
        echo "run_id=$run_id" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
    
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: fester-honker
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.run_id }}
    
    - name: TBD Get Access Token For Box
      run: |
        echo "TBD Use Box API to get a fresh access token"
        cat fester-honker.txt
        echo $(date +%s) > fester-honker.txt
        
    - name: Delete Old fester-honker Artifact   
      run: |
        artifact_id=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
          jq -r '.artifacts[] | select(.name == "fester-honker") | .id')
      
        curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.artifact_id }}"    

    - name: Upload new fester-honker As Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fester-honker
        path: fester-honker.txt
               
    - name: TBD Verify Release Doesn't Already Exist On Box
      run:  | 
        echo "TBD Get List of Releases From Box"
        echo "TBD If Release Already Exists Then Exit With Error"
    
    - name: Get Run ID Of Workflow That Created The RC Artifact  
      id: fetch-binaries
      run: |
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=${{ inputs.artifact_name }}" | jq -r '.artifacts[0].workflow_run.id')
        echo "run_id of workflow that produced the artifact is $run_id"
        echo "run_id=$run_id" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
    
    - name: Download RC Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.run_id }}
        
    - name: Extract Version From RC Artifact
      run: |
        version=$(cat ./bin/app-data.js | grep 'version:' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Preparing version $version"
        echo "VERSION=$version" >> $GITHUB_ENV
    
    - name: Create Release Zip File For Box Upload
      run:  | 
        echo "Tarball ./bin and ./node_modules into VMP-Release-${{ env.VERSION }}.zip"
        tar -cvzf VMP-Release-${{ env.VERSION }}.zip ./bin ./node_modules

    - name: Show VMP-Release-${{ env.VERSION }}.zip
      run:  ls -lh *.zip

    - name: TBD Upload VMP-Release-${{ env.VERSION }} To Box
      run: echo "TBD Use DropBox API to Upload Tarball to Box"
      
