name: Create Release

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v2

    - name: Download RC Artifact  
      id: fetch-binaries
      run: |
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=${{ inputs.artifact_name }}" | jq -r '.artifacts[0].workflow_run.id')
        echo "run_id of workflow that produced the artifact is $run_id"
        echo "run_id=$run_id" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
    
    - name: Download Binaries Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.run_id }}
        
    - name: Print app-data.js
      run: cat ./bin/app-data.js

    #- name: Create Release
    #  id: create_release
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    tag_name: ${{ env.VERSION }}
    #    release_name: Release ${{ env.VERSION }}
    #    body: |
    #      Release ${{ env.VERSION }}
    #    draft: false
    #    prerelease: false

    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ${{ inputs.artifact_name }}
    #    path: path/to/artifact
