name: Create Release

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name'
        required: true
permissions:
  contents: write

jobs:
  create_release:
    concurrency:
      group: create_release
    runs-on: ubuntu-latest
    steps:
    - name: Get Run ID Of Workflow That Created The RC Artifact  
      id: fetch-binaries
      run: |
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=${{ inputs.artifact_name }}" | jq -r '.artifacts[0].workflow_run.id')
        echo "run_id of workflow that produced the artifact is $run_id"
        echo "run_id=$run_id" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
    
    - name: Download RC Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.run_id }}
        
    - name: Extract Version From Artifact
      run: |
        version=$(cat ./bin/app-data.js | grep 'version:' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Preparing version $version"
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VMP-Release-${{ env.VERSION }}
        path: |
          ./bin
          ./node_modules

    - name: Checkout Branch For GitHub Pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Set User Name For Git
      run: git config user.name "${{ github.actor }}"

    - name: Build JSON File release_artifacts.json Containing All Release Artifacts
      run: |
        echo "Get List Of All Artifacts"
        all_artifacts=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -c .)
        #echo "$all_artifacts"  
        
        echo "Filter List Of Artifacts For Release Artifacts Only" 
        # release_artifacts=$(echo "$all_artifacts" | jq -r '.artifacts[] | select(.name | test("VMP-Release-[0-9]+\\.[0-9]+\\.[0-9]+"))')
        release_artifacts="["
        release_artifacts+=$(echo "$all_artifacts" | jq -c '.artifacts[] | select(.name | test("VMP-Release-[0-9]+\\.[0-9]+\\.[0-9]+"))' | paste -sd "," -)
        release_artifacts+="]"        
        
        echo "Create release_artifacts.json"
        echo "$release_artifacts" > release_artifacts.json
        cat release_artifacts.json

    - name: Create New index.html From release_artifacts.json
      run: node ./create-release-html.js

    - name: Delete Temp File release_artifacts.json Before Git Commit
      run: rm release_artifacts.json

    - name: Set User Name For Git
      run: git config user.name "${{ github.actor }}"
                
    - name: Commit And Push Changes To Publish Release on GitHub Pages
      run: |
        git add index.html
        git commit -m "Update index.html with latest Vending Machine Project releases"
        git push origin gh-pages
