name: Delete All Artifacts

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "yes" to confirm deletion of all artifacts'
        required: true

jobs:
  delete_all_artifacts:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_delete == 'yes'

    steps:
    - name: List Artifacts
      id: list_artifacts
      run: |
        artifacts=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
          jq -r '.artifacts[].id' | paste -sd "," -)
        echo "ARTIFACTS=$artifacts" >> $GITHUB_ENV

    - name: Delete Artifacts
      run: |
        artifacts=($ARTIFACTS)
        for artifact_id in "${artifacts[@]}"; do
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
        done
