name: Delete Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: 'Artifact ID to delete'
        required: true

jobs:
  delete_artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Delete Artifact
      run: |
        curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ github.event.inputs.artifact_id }}"
