name: Download Artifact

on:
workflow_dispatch:

jobs:
download-artifact:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v2

- name: Download Artifact
run: |
ARTIFACT_NAME=rc-100-binary
RUN_ID=100
TOKEN=${{ secrets.USER_TOKEN }}

curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3.raw" \
-o "$ARTIFACT_NAME.zip" \
"https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts/$ARTIFACT_NAME/zip"
