name: List Accepted Release Candidates

on:
  workflow_dispatch:
  
jobs:
  list_accepted_RCs:
    runs-on: ubuntu-latest
    steps:
    - name: List Artifacts
      run: |
        curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
          
        #artifact_id=$(curl -s -X GET \
        #  -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
        #  "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
        #  jq -r '.artifacts[] | select(.name == "${{needs.determine_latest_rc.outputs.LATEST_RC}}-binaries") | .id')
        #echo "ARTIFACT_ID=$artifact_id" >> $GITHUB_ENV
       

