name: List Accepted Release Candidates

on:
  workflow_dispatch:
  
jobs:
  list_accepted_RCs:
    runs-on: ubuntu-latest
    steps:
    - name: List Artifacts
      run: |
        artifacts=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts[] | select(.name | test("^rc-[0-9]+-binaries-accepted$")) | "\(.name) - https://api.github.com/repos/${{ github.repository }}/actions/artifacts/\(.id)/zip"')
        echo "$artifacts"
