name: List Rejected Release Candidates

on:
  workflow_dispatch:
  
jobs:
  list_rejected_RCs:
    runs-on: ubuntu-latest
    steps:
    - name: List Artifacts
      run: |
        artifacts=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts[] | select(.name | test("^rc-[0-9]+-binaries-rejected$")) | "Artifact Name: \(.name)\nDownload URL: https://github.com/${{ github.repository }}/actions/runs/\(.workflow_run.id)/artifacts/\(.id)"')
        echo "$artifacts"
