name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  determine_latest_rc:
    concurrency:
      group: acceptance_stage
    runs-on: ubuntu-latest
    outputs:
      LATEST_RC: ${{ steps.get-latest-rc.outputs.LATEST_RC }}
    steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Determine Latest Release Candidate
      id: get-latest-rc
      run: |
        tags=$(git tag -l "rc-*" | grep "rc-*" | sort -V)
        latestRC=$(echo $tags | awk '{print $NF}')
        echo "Latest Release Candidate is $latestRC"
        echo "LATEST_RC=$latestRC" | tee -a $GITHUB_ENV $GITHUB_OUTPUT

    # Check to see artifact rc-<latest rc>-binaries exists. If it doesn't then
    # that means we've already process it.
    - name: Check if artifact exists
      id: check-condition
      run: |
        ARTIFACT_NAME="$latestRC-binary"
        ARTIFACT_EXISTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/artifacts" | jq -r --arg ARTIFACT_NAME "$ARTIFACT_NAME" '.artifacts[] | select(.name == $ARTIFACT_NAME) | .id')
        if [ -n "$ARTIFACT_EXISTS" ]; then
          #echo "CONDITION_MET=true" >> $GITHUB_ENV
          echo "Condition has been met"
        else
          #echo "CONDITION_MET=false" >> $GITHUB_ENV
          echo "Condition has NOT been met"          
        fi
    

  fetch_release_candidate:
    needs: determine_latest_rc
    concurrency:
      group: acceptance_stage
    runs-on: ubuntu-latest

    steps:
    - name: Fetch The Binaries For The RC    
      id: fetch-binaries
      run: |
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=${{ needs.determine_latest_rc.outputs.LATEST_RC }}-binaries" | jq -r '.artifacts[0].workflow_run.id')
        echo "run_id is $run_id"
        echo "run_id=$run_id" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
    
    - name: Download Binaries Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.determine_latest_rc.outputs.LATEST_RC }}-binaries
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.run_id }}
        
    - name: Display downloaded files
      run: ls

    - name: Print app-data.js
      run: cat ./bin/app-data.js

    - name: Run Acceptance Tests
      id: acceptance_tests
      run: |
        chmod a+x node_modules/.bin/jest
        npm run test:acceptance
      continue-on-error: true

    #
    # Acceptance Tests Passed
    #
    - name: Take Action On Acceptance Tests Passed
      if: steps.acceptance_tests.outcome == 'success'
      run: |
        echo "Acceptance Tests PASS"
        # Update the version in app-data.js by dropping the -RC
        sed -i "s/version: \"\([0-9]\+\.[0-9]\+\.[0-9]\+\)-RC\"/version: \"\1\"/g" ./bin/app-data.js
        cat ./bin/app-data.js

    # Upload the proper files ./bin ./node_modules as new artifact rc-<latest rc>-binaries-accepted
    - name: Upload Artifact As Accepted
      if: steps.acceptance_tests.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.determine_latest_rc.outputs.LATEST_RC }}-binaries-accepted
        path: |
          ./bin
          ./node_modules
    #
    # Acceptance Tests Failed
    #
    - name: Take Action On Acceptance Tests Failed
      if: steps.acceptance_tests.outcome != 'success'
      run: |
        echo "Acceptance Tests FAIL"
        
    # Upload the proper files ./bin ./node_modules as new artifact rc-<latest rc>-binaries-rejected
    - name: Upload Artifact As Rejected
      if: steps.acceptance_tests.outcome != 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.determine_latest_rc.outputs.LATEST_RC }}-binaries-rejected
        path: |
          ./bin
          ./node_modules
  
    #
    # Clean up artifacts by deleting original "rc-<latest rc>-binaries" artifact
    # now that we have replaced the artifact as either "rc-<latest rc>-binaries-accepted OR
    # "rc-<latest rc>-binaries-rejected"
    #
    - name: Get latest RC Artifact ID  
      id: get_artifact_id
      run: |
        artifact_id=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
          jq -r '.artifacts[] | select(.name == "${{needs.determine_latest_rc.outputs.LATEST_RC}}-binaries") | .id')
        #echo "<<<<<< ${{needs.determine_latest_rc.outputs.LATEST_RC}}-binaries >>>>>>>"                               
        #echo ">>>>> $artifact_id <<<<<"  
        echo "ARTIFACT_ID=$artifact_id" >> $GITHUB_ENV
        
    # Delete artifact rc-<latest rc>-binaries
    - name: Delete Artifact   
      run: |
        curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}"    
      
    - name: Fail Workflow To Alert User IF Acceptance Tests Failed
      if: steps.acceptance_tests.outcome != 'success'
      run: |
        echo "Acceptance Tests Failed"
         exit 1
       
        
