name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  determine_latest_rc:
    concurrency:
      group: acceptance_stage
    runs-on: ubuntu-latest
    outputs:
      LATEST_RC: ${{ steps.get-latest-rc.outputs.LATEST_RC }}
    steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Determine Latest Release Candidate
      id: get-latest-rc
      run: |
        tags=$(git tag -l "rc-*" | grep "rc-*" | sort -V)
        latestRC=$(echo $tags | awk '{print $NF}')
        echo "Latest Release Candidate is $latestRC"
        echo "LATEST_RC=$latestRC" | tee -a $GITHUB_ENV $GITHUB_OUTPUT

  fetch_release_candidate:
    needs: determine_latest_rc
    concurrency:
      group: acceptance_stage
    runs-on: ubuntu-latest

    steps:
    - name: Fetch The Binaries For The RC    
      id: fetch-binaries
      run: |
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=${{ needs.determine_latest_rc.outputs.LATEST_RC }}-binaries" | jq -r '.artifacts[0].workflow_run.id')
        echo "run_id is $run_id"
        echo "run_id=$run_id" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
    
    - name: Download Binaries Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.determine_latest_rc.outputs.LATEST_RC }}-binaries
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.run_id }}
        
    - name: Display downloaded files
      run: ls

    - name: Print app-data.js
      run: cat ./bin/app-data.js

    - name: Run Acceptance Tests
      id: acceptance_tests
      run: |
        chmod a+x node_modules/.bin/jest
        npm run test:acceptance
      continue-on-error: true

    - name: Take Action On Acceptance Tests Passed
      if: steps.acceptance_tests.outcome == 'success'
      run: echo "Acceptance Tests PASS"

    - name: Take Action On Acceptance Tests Failed
      if: steps.acceptance_tests.outcome != 'success'
      run: |
        echo "Acceptance Tests FAIL"
        exit 1
        
