name: NodeJS Continuous Delivery

on:
  #workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.latest-rc.outputs.latest_rc }}
        fetch-depth: 0

    - name: Determine Latest Release Candidate
      id: latest-rc
      run: |
        tags=$(git tag -l "rc-*" | grep "rc-*" | sort -V)
        latest_rc=$(echo $tags | awk '{print $NF}')
        echo "latest_rc=$latest_rc" >> $GITHUB_ENV
        echo "Latest Release Candidate: $latest_rc"
