name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.latest-rc.outputs.latest_rc }}
        fetch-depth: 0

    - name: Get List of Release Candidate Tags
      id: get-tags
      run: |
        tags=$(git tag -l "rc-*")
        echo "GITHUB_OUTPUT_TAGS=$tags" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

    - name: Determine Latest Release Candidate
      id: latest-rc
      run: |
        tags=($(echo "$GITHUB_OUTPUT_TAGS" | tr ' ' '\n' | grep "rc-*" | sort -t- -k2 -n))
        latest_rc=${tags[-1]}
        echo "GITHUB_OUTPUT_LATEST_RC=$latest_rc" >> $GITHUB_ENV
        echo "Latest Release Candidate: $latest_rc"
