name: NodeJS CI

on:
  pull_request:
    branches: [ "main" ]
    
# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: commit_stage
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Commit Stage Tests (linter)
      run: npm run lint
    - name: Commit Stage Tests (unit tests)      
      run: npm run test:commit
    - name: Merge to main if tests pass 
      if: success()
      run: |
        GITHUB_TOKEN="${{ secrets.USER_TOKEN }}"
        API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
        curl -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL"
    

  
