name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  test_and_deploy:
    concurrency:
      group: acceptance_stage
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.latest-rc.outputs.latest_rc }}
        fetch-depth: 0

    - name: Determine Latest Release Candidate
      id: latest-rc
      run: |
        tags=$(git tag -l "rc-*" | grep "rc-*" | sort -V)
        latest_rc=$(echo $tags | awk '{print $NF}')
        echo "latest_rc=$latest_rc" >> $GITHUB_ENV
        echo "Latest Release Candidate: $latest_rc"

    - name: Fetch The Binary For The RC
      uses: actions/download-artifact@v4
      with:
        name: rc-109-binary
        github-token: ${{ secrets.USER_TOKEN }}
        run-id: 108
        path: ./bin
      
    - name: Extract Archive
      run: |
        tar -xzvf ./bin/rc-binary.tar.gz -C ./bin
        npm run test:acceptance
        
