name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.latest-rc.outputs.latest_rc }}
        fetch-depth: 0

    - name: Get List of Release Candidate Tags
      id: get-tags
      run: |
        tags=$(git tag -l "rc-*")
        IFS=' ' read -ra tags_array <<< "$tags"
        echo "::set-output name=tags::${tags_array[@]}"
      env:
        GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

    - name: Debug Tags
      run: |
        echo "Tags:"
        echo "${{ steps.get-tags.outputs.tags }}"

    - name: Determine Latest Release Candidate
      id: latest-rc
      run: |
        tags=("${{ steps.get-tags.outputs.tags }}")
        latest_rc=$(printf "%s\n" "${tags[@]}" | grep "rc-*" | sort -V | tail -n 1)
        echo "::set-output name=latest_rc::$latest_rc"
        echo "Latest Release Candidate: $latest_rc"
