name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  test_and_deploy:
    concurrency:
      group: acceptance_stage
  
    runs-on: ubuntu-latest

    steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.latest-rc.outputs.latest_rc }}
        fetch-depth: 0

    - name: Determine Latest Release Candidate
      id: latest-rc
      run: |
        tags=$(git tag -l "rc-*" | grep "rc-*" | sort -V)
        latest_rc=$(echo $tags | awk '{print $NF}')
        echo "latest_rc=$latest_rc" >> $GITHUB_ENV
        echo "Latest Release Candidate: $latest_rc"

    - name: Fetch The Binaries For The RC
      uses: actions/download-artifact@v4
      with:
        name: rc-118-binaries
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        # Debug: We will need to find this run-id using the github api
        run-id: 7807196884              
      
    - name: Display downloaded files
      run: ls

    - name: Print app-data.js
      run: cat ./bin/app-data.js

    - name: Run Acceptance Tests
      run: |
        # chmod -R a+x node_modules
        chmod a+x node_modules/jest-cli/bin/jest.js
        chmod a+x node_modules/jest/bin/jest.js
        npm run test:acceptance
      # run: npm --version
      # run: npm run test:acceptance
      # run: npx jest test/acceptance
