name: NodeJS Continuous Delivery

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  determine_latest_rc:
    concurrency:
      group: acceptance_stage
  
    runs-on: ubuntu-latest

    steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Determine Latest Release Candidate
      id: latest-rc
      run: |
        tags=$(git tag -l "rc-*" | grep "rc-*" | sort -V)
        latest_rc=$(echo $tags | awk '{print $NF}')
        echo "latest_rc=$latest_rc" >> $GITHUB_ENV
        echo "Latest Release Candidate: $latest_rc"

  fetch_release_candidate:
    needs: determine_latest_rc
    concurrency:
      group: acceptance_stage
  
    runs-on: ubuntu-latest

    steps:

    - name: Fetch The Binaries For The RC
      id: fetch-binaries
      run: |
        latest_rc=$GITHUB_ENV
        latest_rc=${latest_rc#*=}
        run_id=$(curl -s "https://api.github.com/repos/WoodyB/vending-machine-project/actions/artifacts?name=${latest_rc}-binaries" | jq -r '.artifacts[0].run_id')
        echo "Run ID: $run_id"
        echo "::set-env name=RUN_ID::$run_id"
      
    - name: Download Binaries Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.latest-rc.outputs.latest_rc }}-binaries
        github-token: ${{ secrets.USER_TOKEN }}
        merge-multiple: false
        repository: WoodyB/vending-machine-project
        run-id: ${{ env.RUN_ID }}
      
    - name: Display downloaded files
      run: ls

    - name: Print app-data.js
      run: cat ./bin/app-data.js

    - name: Run Acceptance Tests
      run: |
        chmod a+x node_modules/.bin/jest
        npm run test:acceptance
