name: Prime The Pump

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prime_the_pump:
    concurrency:
      group: prime_the_pump
    runs-on: ubuntu-latest
    steps:
    - name: Delete Old Artifact  
      continue-on-error: true
      run: |
        artifact_id=$(curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
          jq -r '.artifacts[] | select(.name == "fester-honker") | .id')
        
        if [ -n "$artifact_id" ]; then
          echo "Artifact found with ID: $artifact_id. Deleting old artifact."
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
        else
          echo "Artifact not found. Proceeding without deletion."
        fi
      
    - name: Create New Artifact
      run: |
        new_fester_honker="${{ secrets.BOX_START }}"
        new_encryped_fester_honker=$(echo "$new_fester_honker" | openssl enc -e -base64 -pbkdf2 -nopad -nosalt -k ${{secrets.ENCRYPTION_KEY}})
        echo "$new_encrypted_fester_honker" > fester-honker.txt
         
    - name: Upload Encrypted Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fester-honker
        path: ./fester-honker.txt
